# Generated by Django 5.1.6 on 2025-02-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_appuser_appuser_role_idx_appuser_appuser_created_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
